# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'BlueCarApp' do
    pod 'BMSCore', '~> 1.2'
    pod 'BMSAnalytics', '~> 1.1.2'
    pod 'BMSPush', '~> 1.0'
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for bluemix-object-storage-sample1
  pod 'BluemixObjectStorage'
  pod 'BMSSecurity'

end
